# Generated by Django 4.2.5 on 2023-09-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
