# Generated by Django 4.2.1 on 2023-09-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_customer_name_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(default='Customer', max_length=100),
        ),
    ]
