# Generated by Django 4.2.1 on 2023-09-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_status',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(default='Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product_name',
            field=models.CharField(default='Product', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-going', 'On-going'), ('delivered', 'Delivered')], default='Pending', max_length=26),
        ),
    ]
