# Generated by Django 4.2.1 on 2023-09-11 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-going', 'On-going'), ('delivered', 'Delivered')], default='pending', max_length=26),
        ),
    ]
