# Generated by Django 4.2.1 on 2023-09-11 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_delivery_delivery_time_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
