# Generated by Django 4.2.1 on 2023-09-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_remove_delivery_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_status',
        ),
    ]
