# Generated by Django 4.2.1 on 2023-09-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_delivery_delivery_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_unit',
        ),
    ]
