# Generated by Django 4.2.1 on 2023-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_remove_delivery_delivery_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_unit',
            field=models.CharField(choices=[('mins', 'Minutes'), ('hrs', 'Hours')], default='mins', max_length=4),
        ),
        migrations.AddField(
            model_name='delivery',
            name='product_name',
            field=models.CharField(default='Product', max_length=100),
        ),
    ]
