# Generated by Django 4.2.1 on 2023-09-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_delivery_delivery_unit_delivery_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='product_name',
        ),
    ]
