# Generated by Django 4.2.1 on 2023-09-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_remove_delivery_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_unit',
        ),
    ]
