# Generated by Django 4.2.1 on 2023-09-13 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_remove_delivery_delivery_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
