# Generated by Django 4.2.5 on 2023-09-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('is_available', models.BooleanField(default=False)),
                ('quantity_of_items', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
