# Generated by Django 4.2.5 on 2023-09-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
