# Generated by Django 4.2.5 on 2023-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_remove_cart_product'),
        ('product', '0004_alter_product_quantity_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(null=True, related_name='products', to='Cart.cart'),
        ),
    ]
