# Generated by Django 4.2.4 on 2023-09-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
