# Generated by Django 4.2.5 on 2023-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0003_alter_useraccount_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="confirm_password",
            field=models.CharField(max_length=32),
        ),
    ]
