# Generated by Django 4.2.5 on 2023-10-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0004_alter_useraccount_confirm_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="confirm_password",
            field=models.CharField(max_length=128),
        ),
    ]
