# Generated by Django 4.2.5 on 2023-10-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0005_alter_useraccount_confirm_password"),
        ("collection", "0002_ewasterequest_payment_status_ewasterequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ewasterequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="useraccount.useraccount",
            ),
        ),
    ]
