# Generated by Django 4.2.5 on 2023-09-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date"]},
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product_id",
        ),
        migrations.AddField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("pending", "Pending")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
